require "pry"
require "rspec"
require "date"

require_relative "../lib/cage"
require_relative "../lib/employee"
require_relative "../lib/fox"
require_relative "../lib/gorilla"
require_relative "../lib/reptile"
require_relative "../lib/python"
require_relative "../lib/zoo"
